<!-- Core -->
<script src="{{ argon('assets/vendor/jquery/dist/jquery.min.js') }}"></script>
<script src="{{ argon('assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ argon('assets/vendor/js-cookie/js.cookie.js') }}"></script>
<script src="{{ argon('assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js') }}"></script>
<script src="{{ argon('assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js') }}"></script>
<!-- Optional JS -->
<script src="{{ argon('assets/vendor/onscreen/dist/on-screen.umd.min.js') }}"></script>
<script src="{{ argon('assets/vendor/clipboard/dist/clipboard.min.js') }}"></script>
<script src="{{ argon('assets/vendor/sweetalert2/dist/sweetalert2.min.js') }}"></script>
<script src="{{ argon('assets/vendor/bootstrap-notify/bootstrap-notify.min.js') }}"></script>
<script src="{{ argon('assets/vendor/chart.js/dist/Chart.min.js') }}"></script>
<script src="{{ argon('assets/vendor/chart.js/dist/Chart.extension.js') }}"></script>
<script src="{{ argon('assets/vendor/jvectormap-next/jquery-jvectormap.min.js') }}"></script>
<script src="{{ argon('assets/js/vendor/jvectormap/jquery-jvectormap-world-mill.js') }}"></script>
<script src="{{ argon('assets/vendor/select2/dist/js/select2.min.js') }}"></script>
<script src="{{ argon('assets/vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
<script src="{{ argon('assets/vendor/nouislider/distribute/nouislider.min.js') }}"></script>
<script src="{{ argon('assets/vendor/quill/dist/quill.min.js') }}"></script>
<script src="{{ argon('assets/vendor/dropzone/dist/min/dropzone.min.js') }}"></script>
<script src="{{ argon('assets/vendor/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js') }}"></script>
<script src="{{ argon('assets/vendor/jvectormap-next/jquery-jvectormap.min.js') }}"></script>
<script src="{{ argon('assets/js/vendor/jvectormap/jquery-jvectormap-world-mill.js') }}"></script>
<script src="{{ argon('assets/vendor/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ argon('assets/vendor/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ argon('assets/vendor/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ argon('assets/vendor/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ argon('assets/vendor/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ argon('assets/vendor/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
<script src="{{ argon('assets/vendor/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ argon('assets/vendor/datatables.net-select/js/dataTables.select.min.js') }}"></script>
<script src="{{ argon('assets/vendor/list.js/dist/list.min.js') }}"></script>
<script src="{{ argon('assets/vendor/moment/min/moment.min.js') }}"></script>
<script src="{{ argon('assets/vendor/fullcalendar/dist/fullcalendar.min.js') }}"></script>
<script src="{{ argon('assets/vendor/apexcharts/apexcharts.min.js') }}"></script>
<script src="{{ argon('assets/vendor/echarts/echarts.min.js') }}"></script>

<!-- Argon JS -->
<script src="{{ argon('assets/js/argon.js?v=1.1.0') }}"></script>
